version: 2
jobs:
  build:
    branches: 
      ignore: 
        - gh-pages
    docker:
      - image: cypress/base:8
        environment:
          ## this enables colors in the output
          TERM: xterm
          # CYPRESS_baseUrl: http://teselagen.github.io/openVectorEditor/#/Editor
    working_directory: ~/app
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-deps-{{ .Branch }}
            - v1-deps
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - run:
          name: Start server
          command: yarn start
          background: true
      - save_cache:
          key: v1-deps-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache  ## cache both yarn and Cypress!
      - run: $(yarn bin)/cypress run --record --key 5d118c91-6b05-4e6f-899b-17783d834bf5